spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/connectly_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000

# Cloudinary Configuration
cloudinary.cloud-name=diska4x9b
cloudinary.api-key=493323274182787
cloudinary.api-secret=K453jOvJ0mudQ9syChfBmNtFR3o

